platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
  - name: Samples
  - name: logs

params:
  LOGFILE: behave.log

run:
  path: Samples/ci/scripts/showlog.sh
